version: '3'
networks:
  johnny-demo:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"

services:
  ext-jenkins:
    image: jenkins:external
    build: ./jenkins
    volumes:
      - ./jenkins/volumes:/var/jenkins_home
      - ./jenkins/dev/null:/var/jenkins_home/war
      - ./jenkins/dev/null:/var/jenkins_home/plugins
    ports:
      - 3535:8080
      - 50000:50000
    networks:
      - johnny-demo

  ext-jira:
    image: jira:external
    build: ./jira
    volumes:
      - ./jira/volumes/logs:/opt/atlassian/jira/logs
      - ./jira/volumes:/var/atlassian/jira
    ports:
      - 4646:8080
      - 8443:8443
    networks:
      - johnny-demo

  brains-php-fpm:
    image: php-fpm:the-brains
    build: ./brains
    volumes:
      - ./brains/:/var/www/johnny/the-brains
      - ./brains/.env.dist:/var/www/johnny/the-brains/.env
      - ./brains/docker-overrides/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    networks:
      - johnny-demo

  nginx:
    image: nginx
    ports:
      - 8086:80
    volumes:
      - ./brains/:/var/www/johnny/the-brains
      - ./brains/.env.dist:/var/www/johnny/the-brains/.env
      - ./docker/brains-nginx/the-brains.conf:/etc/nginx/conf.d/default.conf
    links:
      - brains-php-fpm
    networks:
      - johnny-demo

  bot-node:
    image: botmaster:the-bot
    build: ./bot
    ports:
      - 5757:8080
    volumes:
      - ./bot/:/usr/src/app
      - ./bot/.env.dist:/usr/src/app/.env
    networks:
      - johnny-demo

  util-cleaner:
    image: kfei/slack-cleaner
    networks:
      - johnny-demo
